from shop.models import Item, Purchase
from django.utils import timezone

granata = Item.objects.create(name='Granata', price=700)
ak = Item.objects.create(name='АК-47', price=4700)
scar = Item.objects.create(name='Scar', price=6000)
vss = Item.objects.create(name='VSS', price=800000)
scs = Item.objects.create(name='SCS', price=70000)
mp = Item.objects.create(name='MP-5', price=500)
usp = Item.objects.create(name='usp', price=150)
mpp = Item.objects.create(name='MP-40', price=4000)
famas = Item.objects.create(name='Famas', price=50)
raketa = Item.objects.create(name='Raketa', price=700000)

granata.purchases.create(name='Stive', age=2, date_purchase=timezone.now())
ak.purchases.create(name='xqs', age=27, date_purchase=timezone.now())
scar.purchases.create(name='Papich', age=31, date_purchase=timezone.now())
vss.purchases.create(name='Rick', age=72, date_purchase=timezone.now())
scs.purchases.create(name='Morty', age=13, date_purchase=timezone.now())
mp.purchases.create(name='Hesus', age=30, date_purchase=timezone.now())
usp.purchases.create(name='Evelon', age=24, date_purchase=timezone.now())
mpp.purchases.create(name='Masrlovvv', age=23, date_purchase=timezone.now())
famas.purchases.create(name='Tanya', age=11, date_purchase=timezone.now())
raketa.purchases.create(name='Dadya Bogdan', age=100, date_purchase=timezone.now())
granata.purchases.create(name='JoJo', age=222, date_purchase=timezone.now())
ak.purchases.create(name='Toji', age=21, date_purchase=timezone.now())
scar.purchases.create(name='Tor', age=114, date_purchase=timezone.now())
vss.purchases.create(name='Loki', age=23, date_purchase=timezone.now())
scs.purchases.create(name='Dipper', age=13, date_purchase=timezone.now())
mp.purchases.create(name='Titana', age=1, date_purchase=timezone.now())
usp.purchases.create(name='Papys', age=60, date_purchase=timezone.now())
mpp.purchases.create(name='Mamys', age=200, date_purchase=timezone.now())
famas.purchases.create(name='Doter', age=8, date_purchase=timezone.now())
raketa.purchases.create(name='Gensh', age=0, date_purchase=timezone.now())

granata.purchases.all()
ak.purchases.all()
scar.purchases.all()
vss.purchases.all()
scs.purchases.all()
mp.purchases.all()
usp.purchases.all()
mpp.purchases.all()
famas.purchases.all()
raketa.purchases.all()
